# Generated by Django 5.0.7 on 2024-07-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('annee_sortie', models.CharField(max_length=4)),
                ('date_diner', models.DateField()),
                ('diner_precedent', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3)),
            ],
        ),
    ]
