# Generated by Django 5.0.7 on 2024-07-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_diner',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='annee_sortie',
            field=models.DateField(),
        ),
    ]
